spring:
  application:
    name: discovery-service
  # config:
  #   import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8081/}
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  server:
    waitTimeInMsWhenSyncEmpty: 0
management:
  endpoints:
    web:
      exposure:
        include: "*"

debug: true