server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    instance-id: ${EUREKA_INSTANCE_HOSTNAME:localhost}:${server.port}
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: >
        http://peer1.local:8761/eureka/,
        http://peer2.local:8762/eureka/,
        http://peer3.local:8763/eureka/

---
# Optional: cấu hình Spring Actuator để xem status
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
