#spring:
#  cloud:
#    config:
#      uri: http://localhost:8888
#  profiles:
#    active: native

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false

#server:
#  port: 8761
#debug: true
